unifiedjs/unified-language-server

.vscode/launch.json

based off https://github.com/microsoft/vscode-extension-samples/blob/master/lsp-sample/.vscode/launch.json
Allows launching client and server in debug mode from inside vscode.

build: add vscode debug launch configuration

---

lib/index.js
readme.md
test/index.js
test/test-plugin.js

This implements manual quick fixes (**not to be confused with auto fixes!**) by replacing the reported range with values taken from the `expected` array on vfile messages.

Add support for VS Code Quick Fixes

---

test/index.js
test/test-plugin.js

This is really handled by unified-engine, but it’s nice to assert how the language server handles these situations.

Add tests for previously undefined behavior on errors

---

lib/index.js
readme.md
test/index.js

This is mainly to handle the situation if plugins are not available in certain situations. I.e. if remark language server is started in a project where `remark-parse` or `remark-stringify` is not available.

Add support for passing a processor

---

lib/index.js
package.json
readme.md
test/index.js
test/missing-package-with-default.js
test/missing-package.js
test/remark-with-error.js
test/remark-with-warnings.js

*   This adds support for loading a local processor (such as `rehype`)
from the file system (`node_modules/`) in the project
*   By default, it now shows a warningh notification when that
processor can’t be found locally, instead of throwing an error
*   Optionally, a default processor can be passed when creating the
language server, which will be used if a local processor can’t be
found, instead of the previously mentioned warning notification
Related to: remarkjs/remark-language-server#3.

Add support for loading local processors

---

lib/index.js
package.json
readme.md
test/folder/remark-with-cwd.js
test/index.js
test/remark-with-cwd.js

This adds support for workspaces, which in most cases will be just a simple single workspace (sort of like a working directory on the terminal), but in more complex cases can be multiple workspaces with changes over time.
The closest open workspace is chosen when processing a file, in batches of files that belong together in said workspaces.
For backwards compatibility with LSP 3.6.0, `event.rootUri` is also supported.
Closes GH-20.

Add support for workspaces

---

lib/index.js
test/index.js

Without this fix, the error `Unhandled method client/registerCapability` is thrown when this server is started using `vscode-remark`.
The fix was to move `connection.workspace.onDidChangeWorkspaceFolders()` into `connection.onInitialized()`. The initialize result is now also dynamic based on the reported server capabilities. This setup is based on https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#explaining-the-language-server.

Fix workspace initialization

---

lib/index.js

They just cause annoying XO warnings

Refactor comments

---

lib/index.js

This function was needed to test the language server when everything was
being mocked. Now that the language is actually launched in order to
launch it, this function is no longer necessary.

Remove unneeded test-specific API

---

lib/index.js
package.json
test/index.js

This check was previously deemed unreachable, but it can be reached.
This is based on #35.

Refactor to improve tests

---

lib/index.js

Related-to GH-32.
Closes GH-38.
If for some reason symlinks, weird encodings, funky casings, or whatever are passed in URIs as input over the protocol, then we now respond with exactly that same input value, instead of a by Node.js/us resolved and “normalized” value.

Fix symlinks and more by passing input URIs back

---

lib/index.js

This is just an internal refactor. Upcoming changes will call this function in multiple places, but this way the diffs of those changes will be easier to follow.
One `@ts-expect-error` statement has been changed into a type cast.

Refactor internals

---

.github/workflows/main.yml
lib/index.js
package.json
readme.md
test/index.js

Most notably this means:
- YAML configuration files are strictly parsed as YAML 1.2
- Node.js 12 support has been dropped
- The server now implements LSP 3.17 (which should be backwards compatible)
Some internal changes were needed to make CI pass, but none of them affect the end user.
For details see the [LSP changelog](https://github.com/microsoft/vscode-languageserver-node#3170-protocol-800-json-rpc-800-client-and-800-server) and the [unified-engine release](https://github.com/unifiedjs/unified-engine/releases/tag/10.0.0).

Remove support for Node.js 12, update `unified-engine`

---

test/index.js

IMO This looks slightly nicer than using the named `promises` import. This wasn’t supported yet in Node.js 12.

Refactor to use `fs/promises`

---

test/code-actions.js
test/folder/remark-with-cwd.js
test/index.js
test/missing-package-with-default.js
test/missing-package.js
test/remark-with-cwd.js
test/remark-with-error.js
test/remark-with-warnings.js
test/remark.js

This closer resembles real world usage. It also tests that package exports are properly configured.

Refactor to use export map instead of paths in tests

---

lib/index.js
test/index.js

Refs https://github.com/remarkjs/vscode-remark/issues/113

Fix to ignore document formatting outside workspace

---

lib/index.js
test/code-actions.js
test/index.js

This allows users to fix the issues using auto fix.
Closes #46

Add `isPreferred` to single suggestions for autofixing

---

test/index.js

This allows us to use the console, which is useful for debugging.
This also simplifies how paths are resolved in tests. I combined these changes, because they touch the same lines.

Refactor to use `node-ipc` protocol in tests

---

lib/index.js
package.json

This replaces conversion functions for unist positions to language server ranges with `unist-util-lsp`.

Refactor to use `unist-util-lsp`

---

test/index.js

Killing a child process prevents Node.js from collecting code coverage. The language server process can be stopped gracefully when using stdio, but not when using ipc.

Fix code coverage

---

.gitignore
lib/index.js
readme.md
test/code-actions.js
test/folder/remark-with-cwd.js
test/index.js
test/missing-package-with-default.js
test/missing-package.js
test/remark-with-cwd.js
test/remark-with-error.js
test/remark-with-warnings.js
test/remark.js

Add configuration option requireConfig

---

lib/index.js
test/index.js
test/misconfigured.js

Closes #24
Errors from `unified-engine` are reported as diagnostics on the files the error occurred on. Previously errors were simply unhandled.

Gracefully handle unified-engine errors

---

lib/index.js
package.json
readme.md
test/index.js

The update of the  `find-up` dependency is held back, as it removes support for Node.js 16.

Update dependencies and dev dependencies
